// GENERATED BY cmd/plugins DO NOT EDIT!

package plugins

import (
	p0 "github.com/umputun/reproxy/plugins/demo1"
	p1 "github.com/umputun/reproxy/plugins/demo2"
)

func init() {
	registerPlugin(Plugin{Name: "demo1", Handler: p0.InitPlugin()})
	registerPlugin(Plugin{Name: "demo2", Handler: p1.InitPlugin()})
}
