builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
    dir: app
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ if eq .Os \"darwin\" }}macos{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

brews:
  - name: reproxy
    repository:
      owner: umputun
      name: homebrew-apps
      branch: master
    commit_author:
      name: umputun
      email: umputun@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://reproxy.io"
    description: "Simple edge HTTP(s) reverse proxy with automatic SSL"
    license: "MIT"

nfpms:
  - id: reproxy
    package_name: reproxy
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://reproxy.io
    maintainer: Umputun <umputun@gmail.com>
    description: reverse proxy
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1
    contents:
      - src: reproxy.service
        dst: /etc/systemd/system/reproxy.service
      - src: reproxy-example.yml
        dst: /etc/reproxy-example.yml
        type: config
    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
