FROM  --platform=$BUILDPLATFORM squidfunk/mkdocs-material as build

WORKDIR /build
COPY README.md /build/docs/index.md
COPY site/styles.css /build/docs/stylesheets/extra.css
COPY site/ /build/

RUN sed -i 's|^.*/workflows/ci.yml.*$||' /build/docs/index.md
RUN mkdocs build

COPY site/favicon.svg /build/site/
COPY site/logo.png /build/site/


FROM ghcr.io/umputun/reproxy
COPY --from=build /build/site /srv/site
EXPOSE 8080
USER app
ENTRYPOINT ["/srv/reproxy", "--assets.location=/srv/site"]
