// GENERATED BY cmd/plugins DO NOT EDIT!

package proxy

import (
	p0 "github.com/umputun/reproxy/plugins/demo1"
	p1 "github.com/umputun/reproxy/plugins/demo2"
)

func init() {
	p0.InitPlugin()
	p1.InitPlugin()
}
