package main

import (
	"flag"
	"fmt"
	"os"
)

var (
	packageName   string
	pluginsFolder string
)

func main() {
	flag.StringVar(&packageName, "p", "github.com/umputun/reproxy", "reproxy package name")
	flag.StringVar(&pluginsFolder, "f", "plugins", "plugins folder path")
	flag.Parse()

	if packageName == "" || pluginsFolder == "" {
		flag.Usage()
		os.Exit(1)
	}

	entries, errLoadDir := os.ReadDir(pluginsFolder)
	if errLoadDir != nil {
		fmt.Printf("error loading plugins folder: %s\n", errLoadDir)
		os.Exit(1)
	}

	var plugins []string

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		plugins = append(plugins, entry.Name())
	}

	s := "// GENERATED BY cmd/plugins DO NOT EDIT!\n\npackage proxy\n\nimport (\n\t\"net/http\"\n"

	if len(plugins) > 0 {
		s += "\n"
		for idx, plugin := range plugins {
			fmt.Printf("add plugin: %s\n", plugin)
			s += fmt.Sprintf("\tp%d \"%s/%s/%s\"\n", idx, packageName, pluginsFolder, plugin)
		}
	} else {
		fmt.Printf("no plugins found in %s\n", pluginsFolder)
	}

	s += ")\n\nvar plugins []func(http.Handler) http.Handler\nvar PluginsNames []string\n"

	if len(plugins) > 0 {
		s += "\n"
		s += "func init() {\n"
		for idx, name := range plugins {
			s += fmt.Sprintf("\tPluginsNames = append(PluginsNames, %q)\n", name)
			s += fmt.Sprintf("\tplugins = append(plugins, p%d.Call)\n", idx)
		}
		s += "}\n"
	}

	errWrite := os.WriteFile("app/proxy/plugins.go", []byte(s), 0644)
	if errWrite != nil {
		fmt.Printf("error writing plugins.go: %s\n", errWrite)
		os.Exit(1)
	}
}
