global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: reproxy
    metrics_path: /prometheus
    static_configs:
      - targets:
        - reproxy:8081
