name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  docker:
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yml
    with:
      source_sha: ${{ github.sha }}
      image_tag: ${{ github.ref_name }}
      update_latest: true
    secrets:
      PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  goreleaser:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: set up go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: ~> 1.25
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
